"""Remove temporary column from User model

Revision ID: 34152feb1c23
Revises: f7cab1ae7900
Create Date: 2025-07-23 12:04:19.442100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34152feb1c23'
down_revision = 'f7cab1ae7900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('temp_placeholder')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp_placeholder', sa.VARCHAR(length=1), nullable=True))

    # ### end Alembic commands ###
