"""Add notes column to Attendance table

Revision ID: 6b38076d6eae
Revises: edf87ac14ab1
Create Date: 2025-08-25 12:33:50.369297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b38076d6eae'
down_revision = 'edf87ac14ab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
