"""Correctly add leave_type_id and remove old leave_type column

Revision ID: 913558fb597d
Revises: d671ace666e0
Create Date: 2025-08-06 10:13:28.875397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '913558fb597d'
down_revision = 'd671ace666e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leave_type_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_leave_type', 'leave_types', ['leave_type_id'], ['id'])
        batch_op.drop_column('leave_type')

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.alter_column('rfid_uid',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.alter_column('rfid_uid',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leave_type', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint('fk_leave_type', type_='foreignkey')
        batch_op.drop_column('leave_type_id')

    # ### end Alembic commands ###
