"""Add attendance tracking columns (first_in, last_out, total_duration, status)

Revision ID: b2958e71af5d
Revises: bf6ef33de3f3
Create Date: 2025-07-23 10:50:28.872689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2958e71af5d'
down_revision = 'bf6ef33de3f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_in', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_out', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('total_duration', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('total_duration')
        batch_op.drop_column('last_out')
        batch_op.drop_column('first_in')

    # ### end Alembic commands ###
