"""Add days_of_week to Shift model

Revision ID: d671ace666e0
Revises: 34152feb1c23
Create Date: 2025-08-01 12:40:17.731480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd671ace666e0'
down_revision = '34152feb1c23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('days_of_week', sa.String(length=100), server_default='Mon,Tue,Wed,Thu,Fri'))

    with op.batch_alter_table('shifts', schema=None) as batch_op:
        # Step 2: Alter the column to remove the server_default and set nullable=False
        # This is done in a separate batch because SQLite's ALTER TABLE is limited.
        batch_op.alter_column('days_of_week',
                               existing_type=sa.String(length=100),
                               nullable=False,
                               server_default=None) # Remove the server_default after population

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.drop_column('days_of_week')

    # ### end Alembic commands ###
