"""Add birthdate column to Staff model

Revision ID: edf87ac14ab1
Revises: 1119e399d7f7
Create Date: 2025-08-14 08:53:31.516740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edf87ac14ab1'
down_revision = '1119e399d7f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthdate', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_column('birthdate')

    # ### end Alembic commands ###
