"""Create User table and temporary column for auth setup

Revision ID: f7cab1ae7900
Revises: b2958e71af5d
Create Date: 2025-07-23 12:03:15.439842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7cab1ae7900'
down_revision = 'b2958e71af5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp_placeholder', sa.String(length=1), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('temp_placeholder')

    # ### end Alembic commands ###
